spring:
  jpa:
    show-sql: true

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb

  profiles:
    include: oauth

  # 세션저장소를 JDBC로 선택
  session:
    store-type: jdbc

server:
  servlet:
    encoding:
      force-response: true